### ISSUE TITLE
"babel" field in package.json breaks React Native and potentially other libraries

### ISSUE THREAD

**Issue by migueloller** [acdlite/change-emitter#2]
Hi @acdlite,

I started using `recompose` in a React Native app but the packager wasn't running and throwing the following error:

```
> Error: Couldn't find preset "es2015" relative to directory "./node_modules/change-emitter"
>     at ./node_modules/babel-core/lib/transformation/file/options/option-manager.js:321:17
>     at Array.map (native)
>     at OptionManager.resolvePresets (./node_modules/babel-core/lib/transformation/file/options/option-manager.js:305:20)
>     at OptionManager.mergePresets (./node_modules/babel-core/lib/transformation/file/options/option-manager.js:288:10)
>     at OptionManager.mergeOptions (./node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:14)
>     at OptionManager.init (./node_modules/babel-core/lib/transformation/file/options/option-manager.js:383:12)
>     at File.initOptions (./node_modules/babel-core/lib/transformation/file/index.js:223:65)
>     at new File (./node_modules/babel-core/lib/transformation/file/index.js:140:24)
>     at Pipeline.transform (./node_modules/babel-core/lib/transformation/pipeline.js:46:16)
> TransformError: ./node_modules/change-emitter/lib/index.js: Couldn't find preset "es2015" relative to directory "./node_modules/change-emitter"
```

React Native doesn't like it when there are other `.babelrc`s that don't have the React Native presets (facebook/react-native#8296) and it looks like it doesn't like this either. I double checked the issue was indeed from `change-emitter` by remove the field in the `package.json` and indeed it was.

Is it possible to make this small fix? I wouldn't mind doing a PR myself and moving the settings to a `.babelrc`.

:beer:

**EDIT:** Should I maybe reference this issue in the RN repo as well?

**Comment by acdlite** [comment]
D'oh. I forgot about this. Yeah, a PR would be nice :)

**Comment by javamonn** [comment]
Thanks for getting this fixed! Could you get this published to npm when you get a chance, in order to fix `recompose` in React Native applications? Thanks again!

**Comment by migueloller** [comment]
Hey @acdlite, any chance to know when this fix will be published to npm?

**Comment by migueloller** [comment]
Pinging @acdlite again. 😆

**Comment by willmcclellan** [comment]
Just adding another voice to get this pushed to npm 😃

**Comment by skellock** [comment]
Yes plz.  Just ran into this as well.  An `npm publish` would be super coolsauce.

**Comment by RichardLindhout** [comment]
@acdlite Can you fix this!
